var root_path = (Meteor.settings && Meteor.settings.public && Meteor.settings.public.root) || "";
AccountsTemplates.configure({
    forbidClientAccountCreation: true,
    enablePasswordChange: true,
    showForgotPasswordLink: true,
    onLogoutHook: function(){
        Router.go(root_path);
    }
});

AccountsTemplates.removeField('password');
AccountsTemplates.addField({
    _id: 'password',
    type: 'password',
    placeholder: {
        enrollAccount: "At least six characters"
    },
    required: true,
    minLength: 6,
    re: /(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}/,
    errStr: 'At least 1 digit, 1 lowercase and 1 uppercase'
});

//Routes
AccountsTemplates.configureRoute('changePwd', {
    name: 'changePwd',
    path: root_path + '/change-password',
    redirect: 'user.profile'
});
AccountsTemplates.configureRoute('enrollAccount', {
    name: 'enrollAccount',
    path: root_path + '/enroll-account',
    redirect: 'user.profile'
});
AccountsTemplates.configureRoute('resetPwd', {
    name: 'resetPwd',
    path: root_path + '/reset-password',
    redirect: 'user.profile'
});
AccountsTemplates.configureRoute('signIn', {
    name: 'signIn',
    path: root_path + '/sign-in'
});
AccountsTemplates.configureRoute('forgotPwd', {
    name: 'forgotPwd',
    path: root_path + '/forgot-password',
    redirect: 'donation.form'
});
AccountsTemplates.configureRoute('verifyEmail', {
    path: '/verify-email'
});



if(Meteor.isServer){
    Accounts.emailTemplates.siteName = "Trash Mountain Project";
    Accounts.emailTemplates.from = "Trash Mountain Project<support@trashmountain.com>";

    // Configures "reset-password account" email link
    Accounts.urls.resetPassword = function(token){
        return Meteor.absoluteUrl("reset-password/" + token);
    };
    Accounts.emailTemplates.resetPassword.subject = function (user) {
        return "Reset Your Password.";
    };

    // Configures "enroll-account" email link
    Accounts.urls.enrollAccounts = function(token){
        return "https://trashmountain.com/give/enroll-account/" + token;
    };
    Accounts.emailTemplates.enrollAccount.subject = function (user) {
        return "New giving account.";
    };

    Accounts.emailTemplates.enrollAccount.html = function (user, url) {

        var strVar="";
        strVar += "<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.0 Strict\/\/EN\" \"http:\/\/www.w3.org\/TR\/xhtml1\/DTD\/xhtml1-strict.dtd\">";
        strVar += "<html xmlns=\"http:\/\/www.w3.org\/1999\/xhtml\">";
        strVar += "    <head>";
        strVar += "    	<!-- NAME: FLYER -->";
        strVar += "        <meta http-equiv=\"Content-Type\" content=\"text\/html; charset=UTF-8\">";
        strVar += "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
        strVar += "        <title>*|MC:SUBJECT|*<\/title>";
        strVar += "        ";
        strVar += "    <style type=\"text\/css\">";
        strVar += "		body,#bodyTable,#bodyCell{";
        strVar += "			height:100% !important;";
        strVar += "			margin:0;";
        strVar += "			padding:0;";
        strVar += "			width:100% !important;";
        strVar += "		}";
        strVar += "		table{";
        strVar += "			border-collapse:collapse;";
        strVar += "		}";
        strVar += "		img,a img{";
        strVar += "			border:0;";
        strVar += "			outline:none;";
        strVar += "			text-decoration:none;";
        strVar += "		}";
        strVar += "		h1,h2,h3,h4,h5,h6{";
        strVar += "			margin:0;";
        strVar += "			padding:0;";
        strVar += "		}";
        strVar += "		p{";
        strVar += "			margin:1em 0;";
        strVar += "			padding:0;";
        strVar += "		}";
        strVar += "		a{";
        strVar += "			word-wrap:break-word;";
        strVar += "		}";
        strVar += "		.ReadMsgBody{";
        strVar += "			width:100%;";
        strVar += "		}";
        strVar += "		.ExternalClass{";
        strVar += "			width:100%;";
        strVar += "		}";
        strVar += "		.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div{";
        strVar += "			line-height:100%;";
        strVar += "		}";
        strVar += "		table,td{";
        strVar += "			mso-table-lspace:0pt;";
        strVar += "			mso-table-rspace:0pt;";
        strVar += "		}";
        strVar += "		#outlook a{";
        strVar += "			padding:0;";
        strVar += "		}";
        strVar += "		img{";
        strVar += "			-ms-interpolation-mode:bicubic;";
        strVar += "		}";
        strVar += "		body,table,td,p,a,li,blockquote{";
        strVar += "			-ms-text-size-adjust:100%;";
        strVar += "			-webkit-text-size-adjust:100%;";
        strVar += "		}";
        strVar += "		#bodyCell{";
        strVar += "			padding:0;";
        strVar += "		}";
        strVar += "		.mcnImage{";
        strVar += "			vertical-align:bottom;";
        strVar += "		}";
        strVar += "		.mcnTextContent img{";
        strVar += "			height:auto !important;";
        strVar += "		}";
        strVar += "		a.mcnButton{";
        strVar += "			display:block;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Page";
        strVar += "	@section background style";
        strVar += "	@tip Set the background color and top border for your email. You may want to choose colors that match your company's branding.";
        strVar += "	*\/";
        strVar += "		body,#bodyTable{";
        strVar += "			\/*@editable*\/background-color:#363636;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Page";
        strVar += "	@section background style";
        strVar += "	@tip Set the background color and top border for your email. You may want to choose colors that match your company's branding.";
        strVar += "	*\/";
        strVar += "		#bodyCell{";
        strVar += "			\/*@editable*\/border-top:0;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Page";
        strVar += "	@section heading 1";
        strVar += "	@tip Set the styling for all first-level headings in your emails. These should be the largest of your headings.";
        strVar += "	@style heading 1";
        strVar += "	*\/";
        strVar += "		h1{";
        strVar += "			\/*@editable*\/color:#543680 !important;";
        strVar += "			display:block;";
        strVar += "			\/*@editable*\/font-family:Helvetica;";
        strVar += "			\/*@editable*\/font-size:40px;";
        strVar += "			\/*@editable*\/font-style:normal;";
        strVar += "			\/*@editable*\/font-weight:bold;";
        strVar += "			\/*@editable*\/line-height:100%;";
        strVar += "			\/*@editable*\/letter-spacing:-1px;";
        strVar += "			margin:0;";
        strVar += "			\/*@editable*\/text-align:center;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Page";
        strVar += "	@section heading 2";
        strVar += "	@tip Set the styling for all second-level headings in your emails.";
        strVar += "	@style heading 2";
        strVar += "	*\/";
        strVar += "		h2{";
        strVar += "			\/*@editable*\/color:#404040 !important;";
        strVar += "			display:block;";
        strVar += "			\/*@editable*\/font-family:Helvetica;";
        strVar += "			\/*@editable*\/font-size:26px;";
        strVar += "			\/*@editable*\/font-style:normal;";
        strVar += "			\/*@editable*\/font-weight:bold;";
        strVar += "			\/*@editable*\/line-height:125%;";
        strVar += "			\/*@editable*\/letter-spacing:-.75px;";
        strVar += "			margin:0;";
        strVar += "			\/*@editable*\/text-align:left;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Page";
        strVar += "	@section heading 3";
        strVar += "	@tip Set the styling for all third-level headings in your emails.";
        strVar += "	@style heading 3";
        strVar += "	*\/";
        strVar += "		h3{";
        strVar += "			\/*@editable*\/color:#606060 !important;";
        strVar += "			display:block;";
        strVar += "			\/*@editable*\/font-family:Helvetica;";
        strVar += "			\/*@editable*\/font-size:18px;";
        strVar += "			\/*@editable*\/font-style:normal;";
        strVar += "			\/*@editable*\/font-weight:bold;";
        strVar += "			\/*@editable*\/line-height:125%;";
        strVar += "			\/*@editable*\/letter-spacing:-.5px;";
        strVar += "			margin:0;";
        strVar += "			\/*@editable*\/text-align:left;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Page";
        strVar += "	@section heading 4";
        strVar += "	@tip Set the styling for all fourth-level headings in your emails. These should be the smallest of your headings.";
        strVar += "	@style heading 4";
        strVar += "	*\/";
        strVar += "		h4{";
        strVar += "			\/*@editable*\/color:#808080 !important;";
        strVar += "			display:block;";
        strVar += "			\/*@editable*\/font-family:Helvetica;";
        strVar += "			\/*@editable*\/font-size:16px;";
        strVar += "			\/*@editable*\/font-style:normal;";
        strVar += "			\/*@editable*\/font-weight:bold;";
        strVar += "			\/*@editable*\/line-height:125%;";
        strVar += "			\/*@editable*\/letter-spacing:normal;";
        strVar += "			margin:0;";
        strVar += "			\/*@editable*\/text-align:left;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Preheader";
        strVar += "	@section preheader style";
        strVar += "	@tip Set the background color and borders for your email's preheader area.";
        strVar += "	*\/";
        strVar += "		#templatePreheader{";
        strVar += "			\/*@editable*\/background-color:#FFFFFF;";
        strVar += "			\/*@editable*\/border-top:0;";
        strVar += "			\/*@editable*\/border-bottom:1px solid #D5D5D5;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Preheader";
        strVar += "	@section preheader text";
        strVar += "	@tip Set the styling for your email's preheader text. Choose a size and color that is easy to read.";
        strVar += "	*\/";
        strVar += "		.preheaderContainer .mcnTextContent,.preheaderContainer .mcnTextContent p{";
        strVar += "			\/*@editable*\/color:#606060;";
        strVar += "			\/*@editable*\/font-family:Helvetica;";
        strVar += "			\/*@editable*\/font-size:11px;";
        strVar += "			\/*@editable*\/line-height:125%;";
        strVar += "			\/*@editable*\/text-align:left;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Preheader";
        strVar += "	@section preheader link";
        strVar += "	@tip Set the styling for your email's header links. Choose a color that helps them stand out from your text.";
        strVar += "	*\/";
        strVar += "		.preheaderContainer .mcnTextContent a{";
        strVar += "			\/*@editable*\/color:#26ABE2;";
        strVar += "			\/*@editable*\/font-weight:normal;";
        strVar += "			\/*@editable*\/text-decoration:underline;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Header";
        strVar += "	@section header style";
        strVar += "	@tip Set the background color and borders for your email's header area.";
        strVar += "	*\/";
        strVar += "		#templateHeader{";
        strVar += "			\/*@editable*\/background-color:#EEEEEE;";
        strVar += "			\/*@editable*\/border-top:0;";
        strVar += "			\/*@editable*\/border-bottom:0;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Header";
        strVar += "	@section header text";
        strVar += "	@tip Set the styling for your email's header text. Choose a size and color that is easy to read.";
        strVar += "	*\/";
        strVar += "		.headerContainer .mcnTextContent,.headerContainer .mcnTextContent p{";
        strVar += "			\/*@editable*\/color:#606060;";
        strVar += "			\/*@editable*\/font-family:Helvetica;";
        strVar += "			\/*@editable*\/font-size:15px;";
        strVar += "			\/*@editable*\/line-height:150%;";
        strVar += "			\/*@editable*\/text-align:left;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Header";
        strVar += "	@section header link";
        strVar += "	@tip Set the styling for your email's header links. Choose a color that helps them stand out from your text.";
        strVar += "	*\/";
        strVar += "		.headerContainer .mcnTextContent a{";
        strVar += "			\/*@editable*\/color:#26ABE2;";
        strVar += "			\/*@editable*\/font-weight:normal;";
        strVar += "			\/*@editable*\/text-decoration:underline;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Body";
        strVar += "	@section body style";
        strVar += "	@tip Set the background color and borders for your email's body area.";
        strVar += "	*\/";
        strVar += "		#templateBody{";
        strVar += "			\/*@editable*\/background-color:#EEEEEE;";
        strVar += "			\/*@editable*\/border-top:0;";
        strVar += "			\/*@editable*\/border-bottom:0;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Body";
        strVar += "	@section body container";
        strVar += "	@tip Set the background color and border for your email's body text container.";
        strVar += "	*\/";
        strVar += "		#bodyBackground{";
        strVar += "			\/*@editable*\/background-color:#FFFFFF;";
        strVar += "			\/*@editable*\/border:1px solid #D5D5D5;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Body";
        strVar += "	@section body text";
        strVar += "	@tip Set the styling for your email's body text. Choose a size and color that is easy to read.";
        strVar += "	*\/";
        strVar += "		.bodyContainer .mcnTextContent,.bodyContainer .mcnTextContent p{";
        strVar += "			\/*@editable*\/color:#606060;";
        strVar += "			\/*@editable*\/font-family:Helvetica;";
        strVar += "			\/*@editable*\/font-size:15px;";
        strVar += "			\/*@editable*\/line-height:150%;";
        strVar += "			\/*@editable*\/text-align:left;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Body";
        strVar += "	@section body link";
        strVar += "	@tip Set the styling for your email's body links. Choose a color that helps them stand out from your text.";
        strVar += "	*\/";
        strVar += "		.bodyContainer .mcnTextContent a{";
        strVar += "			\/*@editable*\/color:#26ABE2;";
        strVar += "			\/*@editable*\/font-weight:normal;";
        strVar += "			\/*@editable*\/text-decoration:underline;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Footer";
        strVar += "	@section footer style";
        strVar += "	@tip Set the background color and borders for your email's footer area.";
        strVar += "	*\/";
        strVar += "		#templateFooter{";
        strVar += "			\/*@editable*\/background-color:#363636;";
        strVar += "			\/*@editable*\/border-top:1px solid #000000;";
        strVar += "			\/*@editable*\/border-bottom:0;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Footer";
        strVar += "	@section footer text";
        strVar += "	@tip Set the styling for your email's footer text. Choose a size and color that is easy to read.";
        strVar += "	*\/";
        strVar += "		.footerContainer .mcnTextContent,.footerContainer .mcnTextContent p{";
        strVar += "			\/*@editable*\/color:#CCCCCC;";
        strVar += "			\/*@editable*\/font-family:Helvetica;";
        strVar += "			\/*@editable*\/font-size:11px;";
        strVar += "			\/*@editable*\/line-height:125%;";
        strVar += "			\/*@editable*\/text-align:center;";
        strVar += "		}";
        strVar += "	\/*";
        strVar += "	@tab Footer";
        strVar += "	@section footer link";
        strVar += "	@tip Set the styling for your email's footer links. Choose a color that helps them stand out from your text.";
        strVar += "	*\/";
        strVar += "		.footerContainer .mcnTextContent a{";
        strVar += "			\/*@editable*\/color:#CCCCCC;";
        strVar += "			\/*@editable*\/font-weight:normal;";
        strVar += "			\/*@editable*\/text-decoration:underline;";
        strVar += "		}";
        strVar += "	@media only screen and (max-width: 480px){";
        strVar += "		body,table,td,p,a,li,blockquote{";
        strVar += "			-webkit-text-size-adjust:none !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		body{";
        strVar += "			width:100% !important;";
        strVar += "			min-width:100% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		table[class=mcnTextContentContainer]{";
        strVar += "			width:100% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		table[class=mcnBoxedTextContentContainer]{";
        strVar += "			width:100% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		table[class=mcpreview-image-uploader]{";
        strVar += "			width:100% !important;";
        strVar += "			display:none !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		img[class=mcnImage]{";
        strVar += "			width:100% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		table[class=mcnImageGroupContentContainer]{";
        strVar += "			width:100% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnImageGroupContent]{";
        strVar += "			padding:9px !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnImageGroupBlockInner]{";
        strVar += "			padding-bottom:0 !important;";
        strVar += "			padding-top:0 !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		tbody[class=mcnImageGroupBlockOuter]{";
        strVar += "			padding-bottom:9px !important;";
        strVar += "			padding-top:9px !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		table[class=mcnCaptionTopContent],table[class=mcnCaptionBottomContent]{";
        strVar += "			width:100% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		table[class=mcnCaptionLeftTextContentContainer],table[class=mcnCaptionRightTextContentContainer],table[class=mcnCaptionLeftImageContentContainer],table[class=mcnCaptionRightImageContentContainer],table[class=mcnImageCardLeftTextContentContainer],table[class=mcnImageCardRightTextContentContainer]{";
        strVar += "			width:100% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnImageCardLeftImageContent],td[class=mcnImageCardRightImageContent]{";
        strVar += "			padding-right:18px !important;";
        strVar += "			padding-left:18px !important;";
        strVar += "			padding-bottom:0 !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnImageCardBottomImageContent]{";
        strVar += "			padding-bottom:9px !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnImageCardTopImageContent]{";
        strVar += "			padding-top:18px !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnImageCardLeftImageContent],td[class=mcnImageCardRightImageContent]{";
        strVar += "			padding-right:18px !important;";
        strVar += "			padding-left:18px !important;";
        strVar += "			padding-bottom:0 !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnImageCardBottomImageContent]{";
        strVar += "			padding-bottom:9px !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnImageCardTopImageContent]{";
        strVar += "			padding-top:18px !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		table[class=mcnCaptionLeftContentOuter] td[class=mcnTextContent],table[class=mcnCaptionRightContentOuter] td[class=mcnTextContent]{";
        strVar += "			padding-top:9px !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnCaptionBlockInner] table[class=mcnCaptionTopContent]:last-child td[class=mcnTextContent]{";
        strVar += "			padding-top:18px !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnBoxedTextContentColumn]{";
        strVar += "			padding-left:18px !important;";
        strVar += "			padding-right:18px !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=mcnTextContent]{";
        strVar += "			padding-right:18px !important;";
        strVar += "			padding-left:18px !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		img[class=flexibleImage]{";
        strVar += "			height:auto !important;";
        strVar += "			width:100% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section template width";
        strVar += "	@tip Make the template fluid for portrait or landscape view adaptability. If a fluid layout doesn't work for you, set the width to 300px instead.";
        strVar += "	*\/";
        strVar += "		table[class=templateContainer]{";
        strVar += "			\/*@tab Mobile Styles";
        strVar += "@section template width";
        strVar += "@tip Make the template fluid for portrait or landscape view adaptability. If a fluid layout doesn't work for you, set the width to 300px instead.*\/max-width:600px !important;";
        strVar += "			\/*@editable*\/width:100% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section heading 1";
        strVar += "	@tip Make the first-level headings larger in size for better readability on small screens.";
        strVar += "	*\/";
        strVar += "		h1{";
        strVar += "			\/*@editable*\/font-size:24px !important;";
        strVar += "			\/*@editable*\/line-height:125% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section heading 2";
        strVar += "	@tip Make the second-level headings larger in size for better readability on small screens.";
        strVar += "	*\/";
        strVar += "		h2{";
        strVar += "			\/*@editable*\/font-size:20px !important;";
        strVar += "			\/*@editable*\/line-height:125% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section heading 3";
        strVar += "	@tip Make the third-level headings larger in size for better readability on small screens.";
        strVar += "	*\/";
        strVar += "		h3{";
        strVar += "			\/*@editable*\/font-size:18px !important;";
        strVar += "			\/*@editable*\/line-height:125% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section heading 4";
        strVar += "	@tip Make the fourth-level headings larger in size for better readability on small screens.";
        strVar += "	*\/";
        strVar += "		h4{";
        strVar += "			\/*@editable*\/font-size:16px !important;";
        strVar += "			\/*@editable*\/line-height:125% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section Boxed Text";
        strVar += "	@tip Make the boxed text larger in size for better readability on small screens. We recommend a font size of at least 16px.";
        strVar += "	*\/";
        strVar += "		table[class=mcnBoxedTextContentContainer] td[class=mcnTextContent],td[class=mcnBoxedTextContentContainer] td[class=mcnTextContent] p{";
        strVar += "			\/*@editable*\/font-size:18px !important;";
        strVar += "			\/*@editable*\/line-height:125% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section Preheader Visibility";
        strVar += "	@tip Set the visibility of the email's preheader on small screens. You can hide it to save space.";
        strVar += "	*\/";
        strVar += "		table[id=templatePreheader]{";
        strVar += "			\/*@editable*\/display:block !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section Preheader Text";
        strVar += "	@tip Make the preheader text larger in size for better readability on small screens.";
        strVar += "	*\/";
        strVar += "		td[class=preheaderContainer] td[class=mcnTextContent],td[class=preheaderContainer] td[class=mcnTextContent] p{";
        strVar += "			\/*@editable*\/font-size:14px !important;";
        strVar += "			\/*@editable*\/line-height:115% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section Header Text";
        strVar += "	@tip Make the header text larger in size for better readability on small screens.";
        strVar += "	*\/";
        strVar += "		td[class=headerContainer] td[class=mcnTextContent],td[class=headerContainer] td[class=mcnTextContent] p{";
        strVar += "			\/*@editable*\/font-size:18px !important;";
        strVar += "			\/*@editable*\/line-height:125% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section Body Text";
        strVar += "	@tip Make the body text larger in size for better readability on small screens. We recommend a font size of at least 16px.";
        strVar += "	*\/";
        strVar += "		td[class=bodyContainer] td[class=mcnTextContent],td[class=bodyContainer] td[class=mcnTextContent] p{";
        strVar += "			\/*@editable*\/font-size:18px !important;";
        strVar += "			\/*@editable*\/line-height:125% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "	\/*";
        strVar += "	@tab Mobile Styles";
        strVar += "	@section footer text";
        strVar += "	@tip Make the body content text larger in size for better readability on small screens.";
        strVar += "	*\/";
        strVar += "		td[class=footerContainer] td[class=mcnTextContent],td[class=footerContainer] td[class=mcnTextContent] p{";
        strVar += "			\/*@editable*\/font-size:14px !important;";
        strVar += "			\/*@editable*\/line-height:115% !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}	@media only screen and (max-width: 480px){";
        strVar += "		td[class=footerContainer] a[class=utilityLink]{";
        strVar += "			display:block !important;";
        strVar += "		}";
        strVar += "";
        strVar += "}<\/style><\/head>";
        strVar += "    <body leftmargin=\"0\" marginwidth=\"0\" topmargin=\"0\" marginheight=\"0\" offset=\"0\">";
        strVar += "        <center>";
        strVar += "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\" id=\"bodyTable\">";
        strVar += "                <tr>";
        strVar += "                    <td align=\"center\" valign=\"top\" id=\"bodyCell\">";
        strVar += "                        <!-- BEGIN TEMPLATE \/\/ -->";
        strVar += "                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">";
        strVar += "                            <tr>";
        strVar += "                                <td align=\"center\" valign=\"top\">";
        strVar += "                                    <!-- BEGIN PREHEADER \/\/ -->";
        strVar += "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"templatePreheader\">";
        strVar += "                                        <tr>";
        strVar += "                                        	<td align=\"center\" valign=\"top\">";
        strVar += "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"templateContainer\">";
        strVar += "                                                    <tr>";
        strVar += "                                                        <td valign=\"top\" class=\"preheaderContainer\" style=\"padding-top:10px; padding-bottom:10px;\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\">";
        strVar += "    <tbody class=\"mcnTextBlockOuter\">";
        strVar += "        <tr>";
        strVar += "            <td valign=\"top\" class=\"mcnTextBlockInner\">";
        strVar += "                ";
        strVar += "                <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"mcnTextContentContainer\">";
        strVar += "                    <tbody><tr>";
        strVar += "                        ";
        strVar += "                        <td valign=\"top\" class=\"mcnTextContent\" style=\"padding: 9px 18px;color: #FFFFFF;\">";
        strVar += "                        ";
        strVar += "                            <div style=\"text-align: center;\"><span style=\"color: #222222;font-family: arial,sans-serif;line-height: normal;text-align: center;\">" + Meteor.settings.dev + "We setup an account for you.<\/span><\/div>";
        strVar += "";
        strVar += "                        <\/td>";
        strVar += "                    <\/tr>";
        strVar += "                <\/tbody><\/table>";
        strVar += "                ";
        strVar += "            <\/td>";
        strVar += "        <\/tr>";
        strVar += "    <\/tbody>";
        strVar += "<\/table><\/td>";
        strVar += "                                                    <\/tr>";
        strVar += "                                                <\/table>";
        strVar += "                                            <\/td>                                            ";
        strVar += "                                        <\/tr>";
        strVar += "                                    <\/table>";
        strVar += "                                    <!-- \/\/ END PREHEADER -->";
        strVar += "                                <\/td>";
        strVar += "                            <\/tr>";
        strVar += "                            <tr>";
        strVar += "                                <td align=\"center\" valign=\"top\">";
        strVar += "                                    <!-- BEGIN HEADER \/\/ -->";
        strVar += "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"templateHeader\">";
        strVar += "                                        <tr>";
        strVar += "                                            <td align=\"center\" valign=\"top\">";
        strVar += "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"templateContainer\">";
        strVar += "                                                    <tr>";
        strVar += "                                                        <td valign=\"top\" class=\"headerContainer\" style=\"padding-top:15px; padding-bottom:10px;\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnImageBlock\">";
        strVar += "    <tbody class=\"mcnImageBlockOuter\">";
        strVar += "            <tr>";
        strVar += "                <td valign=\"top\" style=\"padding:9px\" class=\"mcnImageBlockInner\">";
        strVar += "                    <table align=\"left\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnImageContentContainer\">";
        strVar += "                        <tbody><tr>";
        strVar += "                            <td class=\"mcnImageContent\" valign=\"top\" style=\"padding-right: 9px; padding-left: 9px; padding-top: 0; padding-bottom: 0; text-align:center;\">";
        strVar += "                                ";
        strVar += "                                    ";
        strVar += "                                        <img align=\"center\" alt=\"\" src=\"https:\/\/gallery.mailchimp.com\/d887dd608b616111eec3c67a7\/images\/0ead8c57-3599-4a6b-a7df-01e875942326.png\" width=\"125\" style=\"max-width:250px; padding-bottom: 0; display: inline !important; vertical-align: bottom;\" class=\"mcnImage\">";
        strVar += "                                    ";
        strVar += "                                ";
        strVar += "                            <\/td>";
        strVar += "                        <\/tr>";
        strVar += "                    <\/tbody><\/table>";
        strVar += "                <\/td>";
        strVar += "            <\/tr>";
        strVar += "    <\/tbody>";
        strVar += "<\/table><\/td>";
        strVar += "                                                    <\/tr>";
        strVar += "                                                <\/table>";
        strVar += "                                            <\/td>";
        strVar += "                                        <\/tr>";
        strVar += "                                    <\/table>";
        strVar += "                                    <!-- \/\/ END HEADER -->";
        strVar += "                                <\/td>";
        strVar += "                            <\/tr>";
        strVar += "                            <tr>";
        strVar += "                                <td align=\"center\" valign=\"top\">";
        strVar += "                                    <!-- BEGIN BODY \/\/ -->";
        strVar += "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"templateBody\">";
        strVar += "                                        <tr>";
        strVar += "                                            <td align=\"center\" valign=\"top\" style=\"padding-top:10px; padding-right:10px; padding-bottom:5px; padding-left:10px;\">";
        strVar += "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"templateContainer\">";
        strVar += "                                                    <tr>";
        strVar += "                                                        <td align=\"center\" valign=\"top\">";
        strVar += "                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"bodyBackground\">";
        strVar += "                                                                <tr>";
        strVar += "                                                                    <td valign=\"top\" class=\"bodyContainer\" style=\"padding-top:10px; padding-bottom:10px;\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnButtonBlock\">";
        strVar += "    <tbody class=\"mcnButtonBlockOuter\">";
        strVar += "        <tr>";
        strVar += "            <td style=\"padding-top:0; padding-right:18px; padding-bottom:18px; padding-left:18px;\" valign=\"top\" align=\"center\" class=\"mcnButtonBlockInner\">";
        strVar += "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnButtonContentContainer\" style=\"border-collapse: separate !important;border: 2px solid #CCCCCC;border-radius: 5px;background-color: #7DCC78;\">";
        strVar += "                    <tbody>";
        strVar += "                        <tr>";
        strVar += "                            <td align=\"center\" valign=\"middle\" class=\"mcnButtonContent\" style=\"font-family: Arial; font-size: 16px; padding: 16px;\">";
        strVar += "                                <a class=\"mcnButton \" title=\"Complete Account Setup\" href=" + url + " target=\"_blank\" style=\"font-weight: bold;letter-spacing: normal;line-height: 100%;text-align: center;text-decoration: none;color: #FFFFFF;\">Complete Account Setup<\/a>";
        strVar += "                            <\/td>";
        strVar += "                        <\/tr>";
        strVar += "                    <\/tbody>";
        strVar += "                <\/table>";
        strVar += "            <\/td>";
        strVar += "        <\/tr>";
        strVar += "    <\/tbody>";
        strVar += "<\/table><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\">";
        strVar += "    <tbody class=\"mcnTextBlockOuter\">";
        strVar += "        <tr>";
        strVar += "            <td valign=\"top\" class=\"mcnTextBlockInner\">";
        strVar += "                ";
        strVar += "                <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"599\" class=\"mcnTextContentContainer\">";
        strVar += "                    <tbody><tr>";
        strVar += "                        ";
        strVar += "                        <td valign=\"top\" class=\"mcnTextContent\" style=\"padding-top:9px; padding-right: 18px; padding-bottom: 9px; padding-left: 18px;\">";
        strVar += "                        ";
        strVar += "                            <span style=\"font-size:12px; line-height:20.7999992370605px\"><strong>We set you up with a user account for our giving page.<\/strong><\/span><br>";
        strVar += "<span style=\"font-size:12px; line-height:20.7999992370605px\">Your username is your email address.&nbsp;<br>";
        strVar += "<br>";
        strVar += "<strong>To complete the account setup click the button at the top of this email.&nbsp;If you prefer not to have a user account you don't have to do anything, the account will only activate if you use the button.&nbsp;<br>";
        strVar += "<br>";
        strVar += "<strong>Why did you setup an account for me?<\/strong><br>";
        strVar += "We noticed that many of our partners give monthly, but they do it manually each time. We wanted to make it easier to give this way. Once you are in your new account you can give from there and save you payment method for quicker giving in the future. The user profile page also shows all of your gifts to Trash Mountain Project, your total giving and more.<br>";
        strVar += "<br>";
        strVar += "<strong>Have feedback?<\/strong><br>";
        strVar += "Email us --&gt;&nbsp;<a href=\"mailto:support@trashmountain.com?subject=Account%20feedback\" target=\"_blank\">support@trashmountain.com<\/a><\/span>";
        strVar += "                        <\/td>";
        strVar += "                    <\/tr>";
        strVar += "                <\/tbody><\/table>";
        strVar += "                ";
        strVar += "            <\/td>";
        strVar += "        <\/tr>";
        strVar += "    <\/tbody>";
        strVar += "<\/table><\/td>";
        strVar += "                                                                <\/tr>";
        strVar += "                                                            <\/table>";
        strVar += "                                                        <\/td>";
        strVar += "                                                    <\/tr>";
        strVar += "                                                    <tr>";
        strVar += "                                                        <td align=\"center\" valign=\"top\">";
        strVar += "                                                            <img src=\"http:\/\/gallery.mailchimp.com\/27aac8a65e64c994c4416d6b8\/images\/couponshadow.png\" height=\"20\" width=\"600\" class=\"flexibleImage\" style=\"display:block; max-width:560px;\">";
        strVar += "                                                        <\/td>";
        strVar += "                                                    <\/tr>";
        strVar += "                                                <\/table>";
        strVar += "                                            <\/td>";
        strVar += "                                        <\/tr>";
        strVar += "                                    <\/table>";
        strVar += "                                    <!-- \/\/ END BODY -->";
        strVar += "                                <\/td>";
        strVar += "                            <\/tr>";
        strVar += "                            <tr>";
        strVar += "                                <td align=\"center\" valign=\"top\" style=\"padding-bottom:40px;\">";
        strVar += "                                    <!-- BEGIN FOOTER \/\/ -->";
        strVar += "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"templateFooter\">";
        strVar += "                                        <tr>";
        strVar += "                                            <td align=\"center\" valign=\"top\">";
        strVar += "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"templateContainer\">";
        strVar += "                                                    <tr>";
        strVar += "                                                        <td valign=\"top\" class=\"footerContainer\" style=\"padding-top:10px; padding-bottom:10px;\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\">";
        strVar += "    <tbody class=\"mcnTextBlockOuter\">";
        strVar += "        <tr>";
        strVar += "            <td valign=\"top\" class=\"mcnTextBlockInner\">";
        strVar += "                ";
        strVar += "                <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"mcnTextContentContainer\">";
        strVar += "                    <tbody><tr>";
        strVar += "                        ";
        strVar += "                        <td valign=\"top\" class=\"mcnTextContent\" style=\"padding-top:9px; padding-right: 18px; padding-bottom: 9px; padding-left: 18px;\">";
        strVar += "                        ";
        strVar += "                            <span style=\"color:#333333\"><\/span>";
        strVar += "                        <\/td>";
        strVar += "                    <\/tr>";
        strVar += "                <\/tbody><\/table>";
        strVar += "                ";
        strVar += "            <\/td>";
        strVar += "        <\/tr>";
        strVar += "    <\/tbody>";
        strVar += "<\/table><\/td>";
        strVar += "                                                    <\/tr>";
        strVar += "                                                <\/table>";
        strVar += "                                            <\/td>";
        strVar += "                                        <\/tr>";
        strVar += "                                    <\/table>";
        strVar += "                                    <!-- \/\/ END FOOTER -->";
        strVar += "                                <\/td>";
        strVar += "                            <\/tr>";
        strVar += "                        <\/table>";
        strVar += "                        <!-- \/\/ END TEMPLATE -->";
        strVar += "                    <\/td>";
        strVar += "                <\/tr>";
        strVar += "            <\/table>";
        strVar += "        <\/center>";
        strVar += "    <\/body>";
        strVar += "<\/html>";

        return strVar;
    };

        Accounts.emailTemplates.resetPassword.html = function (user, url) {
            var strVar="";
            strVar += "<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.0 Strict\/\/EN\" \"http:\/\/www.w3.org\/TR\/xhtml1\/DTD\/xhtml1-strict.dtd\">";
            strVar += "<html xmlns=\"http:\/\/www.w3.org\/1999\/xhtml\">";
            strVar += "    <head>";
            strVar += "    	<!-- NAME: FLYER -->";
            strVar += "        <meta http-equiv=\"Content-Type\" content=\"text\/html; charset=UTF-8\">";
            strVar += "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
            strVar += "        <title>*|MC:SUBJECT|*<\/title>";
            strVar += "        ";
            strVar += "    <style type=\"text\/css\">";
            strVar += "		body,#bodyTable,#bodyCell{";
            strVar += "			height:100% !important;";
            strVar += "			margin:0;";
            strVar += "			padding:0;";
            strVar += "			width:100% !important;";
            strVar += "		}";
            strVar += "		table{";
            strVar += "			border-collapse:collapse;";
            strVar += "		}";
            strVar += "		img,a img{";
            strVar += "			border:0;";
            strVar += "			outline:none;";
            strVar += "			text-decoration:none;";
            strVar += "		}";
            strVar += "		h1,h2,h3,h4,h5,h6{";
            strVar += "			margin:0;";
            strVar += "			padding:0;";
            strVar += "		}";
            strVar += "		p{";
            strVar += "			margin:1em 0;";
            strVar += "			padding:0;";
            strVar += "		}";
            strVar += "		a{";
            strVar += "			word-wrap:break-word;";
            strVar += "		}";
            strVar += "		.ReadMsgBody{";
            strVar += "			width:100%;";
            strVar += "		}";
            strVar += "		.ExternalClass{";
            strVar += "			width:100%;";
            strVar += "		}";
            strVar += "		.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div{";
            strVar += "			line-height:100%;";
            strVar += "		}";
            strVar += "		table,td{";
            strVar += "			mso-table-lspace:0pt;";
            strVar += "			mso-table-rspace:0pt;";
            strVar += "		}";
            strVar += "		#outlook a{";
            strVar += "			padding:0;";
            strVar += "		}";
            strVar += "		img{";
            strVar += "			-ms-interpolation-mode:bicubic;";
            strVar += "		}";
            strVar += "		body,table,td,p,a,li,blockquote{";
            strVar += "			-ms-text-size-adjust:100%;";
            strVar += "			-webkit-text-size-adjust:100%;";
            strVar += "		}";
            strVar += "		#bodyCell{";
            strVar += "			padding:0;";
            strVar += "		}";
            strVar += "		.mcnImage{";
            strVar += "			vertical-align:bottom;";
            strVar += "		}";
            strVar += "		.mcnTextContent img{";
            strVar += "			height:auto !important;";
            strVar += "		}";
            strVar += "		a.mcnButton{";
            strVar += "			display:block;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Page";
            strVar += "	@section background style";
            strVar += "	@tip Set the background color and top border for your email. You may want to choose colors that match your company's branding.";
            strVar += "	*\/";
            strVar += "		body,#bodyTable{";
            strVar += "			\/*@editable*\/background-color:#363636;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Page";
            strVar += "	@section background style";
            strVar += "	@tip Set the background color and top border for your email. You may want to choose colors that match your company's branding.";
            strVar += "	*\/";
            strVar += "		#bodyCell{";
            strVar += "			\/*@editable*\/border-top:0;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Page";
            strVar += "	@section heading 1";
            strVar += "	@tip Set the styling for all first-level headings in your emails. These should be the largest of your headings.";
            strVar += "	@style heading 1";
            strVar += "	*\/";
            strVar += "		h1{";
            strVar += "			\/*@editable*\/color:#543680 !important;";
            strVar += "			display:block;";
            strVar += "			\/*@editable*\/font-family:Helvetica;";
            strVar += "			\/*@editable*\/font-size:40px;";
            strVar += "			\/*@editable*\/font-style:normal;";
            strVar += "			\/*@editable*\/font-weight:bold;";
            strVar += "			\/*@editable*\/line-height:100%;";
            strVar += "			\/*@editable*\/letter-spacing:-1px;";
            strVar += "			margin:0;";
            strVar += "			\/*@editable*\/text-align:center;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Page";
            strVar += "	@section heading 2";
            strVar += "	@tip Set the styling for all second-level headings in your emails.";
            strVar += "	@style heading 2";
            strVar += "	*\/";
            strVar += "		h2{";
            strVar += "			\/*@editable*\/color:#404040 !important;";
            strVar += "			display:block;";
            strVar += "			\/*@editable*\/font-family:Helvetica;";
            strVar += "			\/*@editable*\/font-size:26px;";
            strVar += "			\/*@editable*\/font-style:normal;";
            strVar += "			\/*@editable*\/font-weight:bold;";
            strVar += "			\/*@editable*\/line-height:125%;";
            strVar += "			\/*@editable*\/letter-spacing:-.75px;";
            strVar += "			margin:0;";
            strVar += "			\/*@editable*\/text-align:left;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Page";
            strVar += "	@section heading 3";
            strVar += "	@tip Set the styling for all third-level headings in your emails.";
            strVar += "	@style heading 3";
            strVar += "	*\/";
            strVar += "		h3{";
            strVar += "			\/*@editable*\/color:#606060 !important;";
            strVar += "			display:block;";
            strVar += "			\/*@editable*\/font-family:Helvetica;";
            strVar += "			\/*@editable*\/font-size:18px;";
            strVar += "			\/*@editable*\/font-style:normal;";
            strVar += "			\/*@editable*\/font-weight:bold;";
            strVar += "			\/*@editable*\/line-height:125%;";
            strVar += "			\/*@editable*\/letter-spacing:-.5px;";
            strVar += "			margin:0;";
            strVar += "			\/*@editable*\/text-align:left;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Page";
            strVar += "	@section heading 4";
            strVar += "	@tip Set the styling for all fourth-level headings in your emails. These should be the smallest of your headings.";
            strVar += "	@style heading 4";
            strVar += "	*\/";
            strVar += "		h4{";
            strVar += "			\/*@editable*\/color:#808080 !important;";
            strVar += "			display:block;";
            strVar += "			\/*@editable*\/font-family:Helvetica;";
            strVar += "			\/*@editable*\/font-size:16px;";
            strVar += "			\/*@editable*\/font-style:normal;";
            strVar += "			\/*@editable*\/font-weight:bold;";
            strVar += "			\/*@editable*\/line-height:125%;";
            strVar += "			\/*@editable*\/letter-spacing:normal;";
            strVar += "			margin:0;";
            strVar += "			\/*@editable*\/text-align:left;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Preheader";
            strVar += "	@section preheader style";
            strVar += "	@tip Set the background color and borders for your email's preheader area.";
            strVar += "	*\/";
            strVar += "		#templatePreheader{";
            strVar += "			\/*@editable*\/background-color:#FFFFFF;";
            strVar += "			\/*@editable*\/border-top:0;";
            strVar += "			\/*@editable*\/border-bottom:1px solid #D5D5D5;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Preheader";
            strVar += "	@section preheader text";
            strVar += "	@tip Set the styling for your email's preheader text. Choose a size and color that is easy to read.";
            strVar += "	*\/";
            strVar += "		.preheaderContainer .mcnTextContent,.preheaderContainer .mcnTextContent p{";
            strVar += "			\/*@editable*\/color:#606060;";
            strVar += "			\/*@editable*\/font-family:Helvetica;";
            strVar += "			\/*@editable*\/font-size:11px;";
            strVar += "			\/*@editable*\/line-height:125%;";
            strVar += "			\/*@editable*\/text-align:left;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Preheader";
            strVar += "	@section preheader link";
            strVar += "	@tip Set the styling for your email's header links. Choose a color that helps them stand out from your text.";
            strVar += "	*\/";
            strVar += "		.preheaderContainer .mcnTextContent a{";
            strVar += "			\/*@editable*\/color:#26ABE2;";
            strVar += "			\/*@editable*\/font-weight:normal;";
            strVar += "			\/*@editable*\/text-decoration:underline;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Header";
            strVar += "	@section header style";
            strVar += "	@tip Set the background color and borders for your email's header area.";
            strVar += "	*\/";
            strVar += "		#templateHeader{";
            strVar += "			\/*@editable*\/background-color:#EEEEEE;";
            strVar += "			\/*@editable*\/border-top:0;";
            strVar += "			\/*@editable*\/border-bottom:0;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Header";
            strVar += "	@section header text";
            strVar += "	@tip Set the styling for your email's header text. Choose a size and color that is easy to read.";
            strVar += "	*\/";
            strVar += "		.headerContainer .mcnTextContent,.headerContainer .mcnTextContent p{";
            strVar += "			\/*@editable*\/color:#606060;";
            strVar += "			\/*@editable*\/font-family:Helvetica;";
            strVar += "			\/*@editable*\/font-size:15px;";
            strVar += "			\/*@editable*\/line-height:150%;";
            strVar += "			\/*@editable*\/text-align:left;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Header";
            strVar += "	@section header link";
            strVar += "	@tip Set the styling for your email's header links. Choose a color that helps them stand out from your text.";
            strVar += "	*\/";
            strVar += "		.headerContainer .mcnTextContent a{";
            strVar += "			\/*@editable*\/color:#26ABE2;";
            strVar += "			\/*@editable*\/font-weight:normal;";
            strVar += "			\/*@editable*\/text-decoration:underline;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Body";
            strVar += "	@section body style";
            strVar += "	@tip Set the background color and borders for your email's body area.";
            strVar += "	*\/";
            strVar += "		#templateBody{";
            strVar += "			\/*@editable*\/background-color:#EEEEEE;";
            strVar += "			\/*@editable*\/border-top:0;";
            strVar += "			\/*@editable*\/border-bottom:0;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Body";
            strVar += "	@section body container";
            strVar += "	@tip Set the background color and border for your email's body text container.";
            strVar += "	*\/";
            strVar += "		#bodyBackground{";
            strVar += "			\/*@editable*\/background-color:#FFFFFF;";
            strVar += "			\/*@editable*\/border:1px solid #D5D5D5;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Body";
            strVar += "	@section body text";
            strVar += "	@tip Set the styling for your email's body text. Choose a size and color that is easy to read.";
            strVar += "	*\/";
            strVar += "		.bodyContainer .mcnTextContent,.bodyContainer .mcnTextContent p{";
            strVar += "			\/*@editable*\/color:#606060;";
            strVar += "			\/*@editable*\/font-family:Helvetica;";
            strVar += "			\/*@editable*\/font-size:15px;";
            strVar += "			\/*@editable*\/line-height:150%;";
            strVar += "			\/*@editable*\/text-align:left;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Body";
            strVar += "	@section body link";
            strVar += "	@tip Set the styling for your email's body links. Choose a color that helps them stand out from your text.";
            strVar += "	*\/";
            strVar += "		.bodyContainer .mcnTextContent a{";
            strVar += "			\/*@editable*\/color:#26ABE2;";
            strVar += "			\/*@editable*\/font-weight:normal;";
            strVar += "			\/*@editable*\/text-decoration:underline;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Footer";
            strVar += "	@section footer style";
            strVar += "	@tip Set the background color and borders for your email's footer area.";
            strVar += "	*\/";
            strVar += "		#templateFooter{";
            strVar += "			\/*@editable*\/background-color:#363636;";
            strVar += "			\/*@editable*\/border-top:1px solid #000000;";
            strVar += "			\/*@editable*\/border-bottom:0;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Footer";
            strVar += "	@section footer text";
            strVar += "	@tip Set the styling for your email's footer text. Choose a size and color that is easy to read.";
            strVar += "	*\/";
            strVar += "		.footerContainer .mcnTextContent,.footerContainer .mcnTextContent p{";
            strVar += "			\/*@editable*\/color:#CCCCCC;";
            strVar += "			\/*@editable*\/font-family:Helvetica;";
            strVar += "			\/*@editable*\/font-size:11px;";
            strVar += "			\/*@editable*\/line-height:125%;";
            strVar += "			\/*@editable*\/text-align:center;";
            strVar += "		}";
            strVar += "	\/*";
            strVar += "	@tab Footer";
            strVar += "	@section footer link";
            strVar += "	@tip Set the styling for your email's footer links. Choose a color that helps them stand out from your text.";
            strVar += "	*\/";
            strVar += "		.footerContainer .mcnTextContent a{";
            strVar += "			\/*@editable*\/color:#CCCCCC;";
            strVar += "			\/*@editable*\/font-weight:normal;";
            strVar += "			\/*@editable*\/text-decoration:underline;";
            strVar += "		}";
            strVar += "	@media only screen and (max-width: 480px){";
            strVar += "		body,table,td,p,a,li,blockquote{";
            strVar += "			-webkit-text-size-adjust:none !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		body{";
            strVar += "			width:100% !important;";
            strVar += "			min-width:100% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		table[class=mcnTextContentContainer]{";
            strVar += "			width:100% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		table[class=mcnBoxedTextContentContainer]{";
            strVar += "			width:100% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		table[class=mcpreview-image-uploader]{";
            strVar += "			width:100% !important;";
            strVar += "			display:none !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		img[class=mcnImage]{";
            strVar += "			width:100% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		table[class=mcnImageGroupContentContainer]{";
            strVar += "			width:100% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnImageGroupContent]{";
            strVar += "			padding:9px !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnImageGroupBlockInner]{";
            strVar += "			padding-bottom:0 !important;";
            strVar += "			padding-top:0 !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		tbody[class=mcnImageGroupBlockOuter]{";
            strVar += "			padding-bottom:9px !important;";
            strVar += "			padding-top:9px !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		table[class=mcnCaptionTopContent],table[class=mcnCaptionBottomContent]{";
            strVar += "			width:100% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		table[class=mcnCaptionLeftTextContentContainer],table[class=mcnCaptionRightTextContentContainer],table[class=mcnCaptionLeftImageContentContainer],table[class=mcnCaptionRightImageContentContainer],table[class=mcnImageCardLeftTextContentContainer],table[class=mcnImageCardRightTextContentContainer]{";
            strVar += "			width:100% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnImageCardLeftImageContent],td[class=mcnImageCardRightImageContent]{";
            strVar += "			padding-right:18px !important;";
            strVar += "			padding-left:18px !important;";
            strVar += "			padding-bottom:0 !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnImageCardBottomImageContent]{";
            strVar += "			padding-bottom:9px !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnImageCardTopImageContent]{";
            strVar += "			padding-top:18px !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnImageCardLeftImageContent],td[class=mcnImageCardRightImageContent]{";
            strVar += "			padding-right:18px !important;";
            strVar += "			padding-left:18px !important;";
            strVar += "			padding-bottom:0 !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnImageCardBottomImageContent]{";
            strVar += "			padding-bottom:9px !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnImageCardTopImageContent]{";
            strVar += "			padding-top:18px !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		table[class=mcnCaptionLeftContentOuter] td[class=mcnTextContent],table[class=mcnCaptionRightContentOuter] td[class=mcnTextContent]{";
            strVar += "			padding-top:9px !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnCaptionBlockInner] table[class=mcnCaptionTopContent]:last-child td[class=mcnTextContent]{";
            strVar += "			padding-top:18px !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnBoxedTextContentColumn]{";
            strVar += "			padding-left:18px !important;";
            strVar += "			padding-right:18px !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=mcnTextContent]{";
            strVar += "			padding-right:18px !important;";
            strVar += "			padding-left:18px !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		img[class=flexibleImage]{";
            strVar += "			height:auto !important;";
            strVar += "			width:100% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section template width";
            strVar += "	@tip Make the template fluid for portrait or landscape view adaptability. If a fluid layout doesn't work for you, set the width to 300px instead.";
            strVar += "	*\/";
            strVar += "		table[class=templateContainer]{";
            strVar += "			\/*@tab Mobile Styles";
            strVar += "@section template width";
            strVar += "@tip Make the template fluid for portrait or landscape view adaptability. If a fluid layout doesn't work for you, set the width to 300px instead.*\/max-width:600px !important;";
            strVar += "			\/*@editable*\/width:100% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section heading 1";
            strVar += "	@tip Make the first-level headings larger in size for better readability on small screens.";
            strVar += "	*\/";
            strVar += "		h1{";
            strVar += "			\/*@editable*\/font-size:24px !important;";
            strVar += "			\/*@editable*\/line-height:125% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section heading 2";
            strVar += "	@tip Make the second-level headings larger in size for better readability on small screens.";
            strVar += "	*\/";
            strVar += "		h2{";
            strVar += "			\/*@editable*\/font-size:20px !important;";
            strVar += "			\/*@editable*\/line-height:125% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section heading 3";
            strVar += "	@tip Make the third-level headings larger in size for better readability on small screens.";
            strVar += "	*\/";
            strVar += "		h3{";
            strVar += "			\/*@editable*\/font-size:18px !important;";
            strVar += "			\/*@editable*\/line-height:125% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section heading 4";
            strVar += "	@tip Make the fourth-level headings larger in size for better readability on small screens.";
            strVar += "	*\/";
            strVar += "		h4{";
            strVar += "			\/*@editable*\/font-size:16px !important;";
            strVar += "			\/*@editable*\/line-height:125% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section Boxed Text";
            strVar += "	@tip Make the boxed text larger in size for better readability on small screens. We recommend a font size of at least 16px.";
            strVar += "	*\/";
            strVar += "		table[class=mcnBoxedTextContentContainer] td[class=mcnTextContent],td[class=mcnBoxedTextContentContainer] td[class=mcnTextContent] p{";
            strVar += "			\/*@editable*\/font-size:18px !important;";
            strVar += "			\/*@editable*\/line-height:125% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section Preheader Visibility";
            strVar += "	@tip Set the visibility of the email's preheader on small screens. You can hide it to save space.";
            strVar += "	*\/";
            strVar += "		table[id=templatePreheader]{";
            strVar += "			\/*@editable*\/display:block !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section Preheader Text";
            strVar += "	@tip Make the preheader text larger in size for better readability on small screens.";
            strVar += "	*\/";
            strVar += "		td[class=preheaderContainer] td[class=mcnTextContent],td[class=preheaderContainer] td[class=mcnTextContent] p{";
            strVar += "			\/*@editable*\/font-size:14px !important;";
            strVar += "			\/*@editable*\/line-height:115% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section Header Text";
            strVar += "	@tip Make the header text larger in size for better readability on small screens.";
            strVar += "	*\/";
            strVar += "		td[class=headerContainer] td[class=mcnTextContent],td[class=headerContainer] td[class=mcnTextContent] p{";
            strVar += "			\/*@editable*\/font-size:18px !important;";
            strVar += "			\/*@editable*\/line-height:125% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section Body Text";
            strVar += "	@tip Make the body text larger in size for better readability on small screens. We recommend a font size of at least 16px.";
            strVar += "	*\/";
            strVar += "		td[class=bodyContainer] td[class=mcnTextContent],td[class=bodyContainer] td[class=mcnTextContent] p{";
            strVar += "			\/*@editable*\/font-size:18px !important;";
            strVar += "			\/*@editable*\/line-height:125% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "	\/*";
            strVar += "	@tab Mobile Styles";
            strVar += "	@section footer text";
            strVar += "	@tip Make the body content text larger in size for better readability on small screens.";
            strVar += "	*\/";
            strVar += "		td[class=footerContainer] td[class=mcnTextContent],td[class=footerContainer] td[class=mcnTextContent] p{";
            strVar += "			\/*@editable*\/font-size:14px !important;";
            strVar += "			\/*@editable*\/line-height:115% !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}	@media only screen and (max-width: 480px){";
            strVar += "		td[class=footerContainer] a[class=utilityLink]{";
            strVar += "			display:block !important;";
            strVar += "		}";
            strVar += "";
            strVar += "}<\/style><\/head>";
            strVar += "    <body leftmargin=\"0\" marginwidth=\"0\" topmargin=\"0\" marginheight=\"0\" offset=\"0\">";
            strVar += "        <center>";
            strVar += "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\" id=\"bodyTable\">";
            strVar += "                <tr>";
            strVar += "                    <td align=\"center\" valign=\"top\" id=\"bodyCell\">";
            strVar += "                        <!-- BEGIN TEMPLATE \/\/ -->";
            strVar += "                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">";
            strVar += "                            <tr>";
            strVar += "                                <td align=\"center\" valign=\"top\">";
            strVar += "                                    <!-- BEGIN PREHEADER \/\/ -->";
            strVar += "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"templatePreheader\">";
            strVar += "                                        <tr>";
            strVar += "                                        	<td align=\"center\" valign=\"top\">";
            strVar += "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"templateContainer\">";
            strVar += "                                                    <tr>";
            strVar += "                                                        <td valign=\"top\" class=\"preheaderContainer\" style=\"padding-top:10px; padding-bottom:10px;\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\">";
            strVar += "    <tbody class=\"mcnTextBlockOuter\">";
            strVar += "        <tr>";
            strVar += "            <td valign=\"top\" class=\"mcnTextBlockInner\">";
            strVar += "                ";
            strVar += "                <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"mcnTextContentContainer\">";
            strVar += "                    <tbody><tr>";
            strVar += "                        ";
            strVar += "                        <td valign=\"top\" class=\"mcnTextContent\" style=\"padding: 9px 18px;color: #FFFFFF;\">";
            strVar += "                        ";
            strVar += "                            <div style=\"text-align: center;\"><span style=\"color: #222222;font-family: arial,sans-serif;line-height: normal;text-align: center;\">" + Meteor.settings.dev + "Reset Your Password.<\/span><\/div>";
            strVar += "";
            strVar += "                        <\/td>";
            strVar += "                    <\/tr>";
            strVar += "                <\/tbody><\/table>";
            strVar += "                ";
            strVar += "            <\/td>";
            strVar += "        <\/tr>";
            strVar += "    <\/tbody>";
            strVar += "<\/table><\/td>";
            strVar += "                                                    <\/tr>";
            strVar += "                                                <\/table>";
            strVar += "                                            <\/td>                                            ";
            strVar += "                                        <\/tr>";
            strVar += "                                    <\/table>";
            strVar += "                                    <!-- \/\/ END PREHEADER -->";
            strVar += "                                <\/td>";
            strVar += "                            <\/tr>";
            strVar += "                            <tr>";
            strVar += "                                <td align=\"center\" valign=\"top\">";
            strVar += "                                    <!-- BEGIN HEADER \/\/ -->";
            strVar += "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"templateHeader\">";
            strVar += "                                        <tr>";
            strVar += "                                            <td align=\"center\" valign=\"top\">";
            strVar += "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"templateContainer\">";
            strVar += "                                                    <tr>";
            strVar += "                                                        <td valign=\"top\" class=\"headerContainer\" style=\"padding-top:15px; padding-bottom:10px;\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnImageBlock\">";
            strVar += "    <tbody class=\"mcnImageBlockOuter\">";
            strVar += "            <tr>";
            strVar += "                <td valign=\"top\" style=\"padding:9px\" class=\"mcnImageBlockInner\">";
            strVar += "                    <table align=\"left\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnImageContentContainer\">";
            strVar += "                        <tbody><tr>";
            strVar += "                            <td class=\"mcnImageContent\" valign=\"top\" style=\"padding-right: 9px; padding-left: 9px; padding-top: 0; padding-bottom: 0; text-align:center;\">";
            strVar += "                                ";
            strVar += "                                    ";
            strVar += "                                        <img align=\"center\" alt=\"\" src=\"https:\/\/gallery.mailchimp.com\/d887dd608b616111eec3c67a7\/images\/0ead8c57-3599-4a6b-a7df-01e875942326.png\" width=\"125\" style=\"max-width:250px; padding-bottom: 0; display: inline !important; vertical-align: bottom;\" class=\"mcnImage\">";
            strVar += "                                    ";
            strVar += "                                ";
            strVar += "                            <\/td>";
            strVar += "                        <\/tr>";
            strVar += "                    <\/tbody><\/table>";
            strVar += "                <\/td>";
            strVar += "            <\/tr>";
            strVar += "    <\/tbody>";
            strVar += "<\/table><\/td>";
            strVar += "                                                    <\/tr>";
            strVar += "                                                <\/table>";
            strVar += "                                            <\/td>";
            strVar += "                                        <\/tr>";
            strVar += "                                    <\/table>";
            strVar += "                                    <!-- \/\/ END HEADER -->";
            strVar += "                                <\/td>";
            strVar += "                            <\/tr>";
            strVar += "                            <tr>";
            strVar += "                                <td align=\"center\" valign=\"top\">";
            strVar += "                                    <!-- BEGIN BODY \/\/ -->";
            strVar += "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"templateBody\">";
            strVar += "                                        <tr>";
            strVar += "                                            <td align=\"center\" valign=\"top\" style=\"padding-top:10px; padding-right:10px; padding-bottom:5px; padding-left:10px;\">";
            strVar += "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"templateContainer\">";
            strVar += "                                                    <tr>";
            strVar += "                                                        <td align=\"center\" valign=\"top\">";
            strVar += "                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"bodyBackground\">";
            strVar += "                                                                <tr>";
            strVar += "                                                                    <td valign=\"top\" class=\"bodyContainer\" style=\"padding-top:10px; padding-bottom:10px;\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnButtonBlock\">";
            strVar += "    <tbody class=\"mcnButtonBlockOuter\">";
            strVar += "        <tr>";
            strVar += "            <td style=\"padding-top:0; padding-right:18px; padding-bottom:18px; padding-left:18px;\" valign=\"top\" align=\"center\" class=\"mcnButtonBlockInner\">";
            strVar += "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnButtonContentContainer\" style=\"border-collapse: separate !important;border: 2px solid #CCCCCC;border-radius: 5px;background-color: #7DCC78;\">";
            strVar += "                    <tbody>";
            strVar += "                        <tr>";
            strVar += "                            <td align=\"center\" valign=\"middle\" class=\"mcnButtonContent\" style=\"font-family: Arial; font-size: 16px; padding: 16px;\">";
            strVar += "                                <a class=\"mcnButton \" title=\"Reset Your Password\" href=" + url + " target=\"_blank\" style=\"font-weight: bold;letter-spacing: normal;line-height: 100%;text-align: center;text-decoration: none;color: #FFFFFF;\">Reset Your Password<\/a>";
            strVar += "                            <\/td>";
            strVar += "                        <\/tr>";
            strVar += "                    <\/tbody>";
            strVar += "                <\/table>";
            strVar += "            <\/td>";
            strVar += "        <\/tr>";
            strVar += "    <\/tbody>";
            strVar += "<\/table><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\">";
            strVar += "    <tbody class=\"mcnTextBlockOuter\">";
            strVar += "        <tr>";
            strVar += "            <td valign=\"top\" class=\"mcnTextBlockInner\">";
            strVar += "                ";
            strVar += "                <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"599\" class=\"mcnTextContentContainer\">";
            strVar += "                    <tbody><tr>";
            strVar += "                        ";
            strVar += "                        <td valign=\"top\" class=\"mcnTextContent\" style=\"padding-top:9px; padding-right: 18px; padding-bottom: 9px; padding-left: 18px;\">";
            strVar += "                        ";
            strVar += "<strong>Have feedback?<\/strong><br>";
            strVar += "Email us --&gt;&nbsp;<a href=\"mailto:support@trashmountain.com?subject=Account%20feedback\" target=\"_blank\">support@trashmountain.com<\/a><\/span>";
            strVar += "                        <\/td>";
            strVar += "                    <\/tr>";
            strVar += "                <\/tbody><\/table>";
            strVar += "                ";
            strVar += "            <\/td>";
            strVar += "        <\/tr>";
            strVar += "    <\/tbody>";
            strVar += "<\/table><\/td>";
            strVar += "                                                                <\/tr>";
            strVar += "                                                            <\/table>";
            strVar += "                                                        <\/td>";
            strVar += "                                                    <\/tr>";
            strVar += "                                                    <tr>";
            strVar += "                                                        <td align=\"center\" valign=\"top\">";
            strVar += "                                                            <img src=\"http:\/\/gallery.mailchimp.com\/27aac8a65e64c994c4416d6b8\/images\/couponshadow.png\" height=\"20\" width=\"600\" class=\"flexibleImage\" style=\"display:block; max-width:560px;\">";
            strVar += "                                                        <\/td>";
            strVar += "                                                    <\/tr>";
            strVar += "                                                <\/table>";
            strVar += "                                            <\/td>";
            strVar += "                                        <\/tr>";
            strVar += "                                    <\/table>";
            strVar += "                                    <!-- \/\/ END BODY -->";
            strVar += "                                <\/td>";
            strVar += "                            <\/tr>";
            strVar += "                            <tr>";
            strVar += "                                <td align=\"center\" valign=\"top\" style=\"padding-bottom:40px;\">";
            strVar += "                                    <!-- BEGIN FOOTER \/\/ -->";
            strVar += "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" id=\"templateFooter\">";
            strVar += "                                        <tr>";
            strVar += "                                            <td align=\"center\" valign=\"top\">";
            strVar += "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"templateContainer\">";
            strVar += "                                                    <tr>";
            strVar += "                                                        <td valign=\"top\" class=\"footerContainer\" style=\"padding-top:10px; padding-bottom:10px;\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\">";
            strVar += "    <tbody class=\"mcnTextBlockOuter\">";
            strVar += "        <tr>";
            strVar += "            <td valign=\"top\" class=\"mcnTextBlockInner\">";
            strVar += "                ";
            strVar += "                <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"mcnTextContentContainer\">";
            strVar += "                    <tbody><tr>";
            strVar += "                        ";
            strVar += "                        <td valign=\"top\" class=\"mcnTextContent\" style=\"padding-top:9px; padding-right: 18px; padding-bottom: 9px; padding-left: 18px;\">";
            strVar += "                        ";
            strVar += "                            <span style=\"color:#333333\"><\/span>";
            strVar += "                        <\/td>";
            strVar += "                    <\/tr>";
            strVar += "                <\/tbody><\/table>";
            strVar += "                ";
            strVar += "            <\/td>";
            strVar += "        <\/tr>";
            strVar += "    <\/tbody>";
            strVar += "<\/table><\/td>";
            strVar += "                                                    <\/tr>";
            strVar += "                                                <\/table>";
            strVar += "                                            <\/td>";
            strVar += "                                        <\/tr>";
            strVar += "                                    <\/table>";
            strVar += "                                    <!-- \/\/ END FOOTER -->";
            strVar += "                                <\/td>";
            strVar += "                            <\/tr>";
            strVar += "                        <\/table>";
            strVar += "                        <!-- \/\/ END TEMPLATE -->";
            strVar += "                    <\/td>";
            strVar += "                <\/tr>";
            strVar += "            <\/table>";
            strVar += "        <\/center>";
            strVar += "    <\/body>";
            strVar += "<\/html>";

            return strVar;
    };
}



